greenelab/hetmech

- hetmech/test_diffusion.py
Tests `copy` argument of `diffusion.dual_normalize` separately.
Splits exponent in `test_dual_normalize_row_and_column_damping` into row and column arguments.
> Separate dual_normalize copy tests

- 1.diffusion-example.ipynb
- 3.dwwc.ipynb
- hetmech/degree_weight.py
- hetmech/diffusion.py
- hetmech/matrix.py
- hetmech/test_diffusion.py
Closes https://github.com/greenelab/hetmech/pull/25
Closes https://github.com/greenelab/hetmech/pull/26
@kkloste, now cypher and matrix implementations of DWWC agree!
> Refactor; Implement DWWC; Split degree_weight and diffusion modules

- 1.diffusion-example.ipynb
- 2.xarray.ipynb
- 3.dwwc.ipynb
- hetmech/degree_weight.py
- hetmech/diffusion.py
- hetmech/matrix.py
- hetmech/test_diffusion.py
- hetmech/xarray.py
> Transpose adjacency matrices so source nodes are rows

- environment.yml
- hetmech/test_degree_weight.py
Tests DWPC computation from https://doi.org/10.1371/journal.pcbi.1004259.g002.
See panel D of:
> Test DW and DWPC computation

- hetmech/degree_weight.py
- hetmech/matrix.py
- hetmech/test_matrix.py
Closes #36 
Edited test_matrix.py to test equality of sparse matrices. Added conversion in degree_weight.py from sparse to dense.
> Add sparse matrix functionality in metaedge_to_adjacency_matrix

- 3.dwwc.ipynb
- hetmech/degree_weight.py
- hetmech/test_degree_weight.py
To save the user the hassle of having to regenerate the names.
> Add row/column names to DWWC output

- hetmech/dwpc.py
This is a new layout file specifically for all the DWPC functions, so that they can be organized nicely, and so that it is easy to see where work has been done and still needs to be done. I would plan to rebase my other open pull requests,  #59, #60, and #61 such that their functions are being put here. I think it definitely makes less sense to have each of those pull requests creating a new file when we will want to bring them all together anyway.
> New file for DWPC

- environment.yml
> add xlrd to environment

- hetmech/hetmat.py
Function to allow read path_counts matrices from a hetmat.
> HetMat: read_path_counts function

- hetmech/hetmat.py
@zietzm this could be mildly useful for #104
> HetMat: function to save matrices

- README.md
@cgreene and @naglem: I realized we hadn't updated the README to acknowledge Pfizer's support. Is there a specific wording or grant number that I should use to acknowledge this grant?
> Update acknowledgements with Pfizer support

- environment.yml
- explore/cache-speeds.ipynb
- hetmech/degree_weight.py
- hetmech/hetmat.py
Co-authored-by: Michael Zietz <michael.zietz@gmail.com>
> In progress caching code

- environment.yml
- hetmech/degree_weight.py
- hetmech/hetmat.py
- hetmech/matrix.py
- hetmech/tests/test_degree_weight.py
Co-authored-by: Michael Zietz <michael.zietz@gmail.com>
> degree_weight: dwwc_method argument & default

- hetmech/degree_weight.py
- hetmech/tests/test_degree_weight.py
> Add support for four-repeats.

- explore/cache-speeds.ipynb
- hetmech/hetmat.py
Refs https://github.com/greenelab/hetmech/issues/108#issuecomment-395075161
> Add get_stats method to cache objects

- hetmech/hetmat/tests/test_caching.py
- hetmech/hetmat/tests/test_hetmat.py
- hetmech/tests/hetnets.py
- hetmech/tests/test_degree_weight.py
- hetmech/tests/test_path_count.py
>  Standardize test hetnets & cache URL reads

- hetmech/hetmat/archive.py
```
Co-authored-by: Michael Zietz <michael.zietz@gmail.com>
```
> create_archive: enable splitting zip output

- hetmech/bulk_computation.py
- hetmech/degree_group.py
- hetmech/hetmat/__init__.py
- hetmech/pipeline.py
This PR includes efficiency upgrades to `degree_group.py` and a new file including useful functions for the bulk computation of DWPC and DGP.
> Bulk computation pipeline

- explore/bulk-pipeline/bulk.ipynb
Completed notebook for all 785 metapaths up to length 3 starting on Disease.
> Bulk computation for all metapaths <= length 3

- environment.yml
https://github.com/numpy/numpy/blob/master/doc/release/1.15.0-notes.rst
https://pandas.pydata.org/pandas-docs/version/0.23.4/whatsnew.html
> Update environment on 2018-08-23

- .travis.yml
- README.md
- environment.yml
upgrades hetio dependency to renamed hetnetpy. Will likely require edits to notebooks before they can be rerun.
> Update conda environment installation
